In [ ]:
!pip install  numpy


In [ ]:
import numpy as np

#Creating numpy:

In [ ]:
a=np.array([1,2,3,])
print(a)

[1 2 3]


In [ ]:
a=np.array([57,68,40])
b=np.array([(1.5,2,3),(4,5,6)])
c=np.array([[[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]]])

In [ ]:
print(a)

[57 68 40]


In [ ]:
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [ ]:
print(c)

[[[[1.5 2.  3. ]
   [4.  5.  6. ]]

  [[3.  2.  1. ]
   [4.  5.  6. ]]]]


In [ ]:
import numpy as np

In [ ]:
a=np.array([[[[40,70,89],[40,79,33],[90,45,69],[900,800,200]]]])

In [ ]:
print(a)

[[[[ 40  70  89]
   [ 40  79  33]
   [ 90  45  69]
   [900 800 200]]]]


In [ ]:
z=np.array([[[[[30,90,50],[80,40,30],[50,30,80]]]]])

In [ ]:
print(z)

[[[[[30 90 50]
    [80 40 30]
    [50 30 80]]]]]


#Initial placeholders:

#create an array of zeros

In [ ]:
np.zeros((19,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((9,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#creating an array of evvenly spaced values(number of samples)

In [ ]:
np.linspace(5,15,15)

array([ 5.        ,  5.71428571,  6.42857143,  7.14285714,  7.85714286,
        8.57142857,  9.28571429, 10.        , 10.71428571, 11.42857143,
       12.14285714, 12.85714286, 13.57142857, 14.28571429, 15.        ])

In [ ]:
np.linspace(3,1,5)

array([3. , 2.5, 2. , 1.5, 1. ])

#create a constant array

##create a 1D array

In [ ]:
e=np.full((10),90)
print(e)
print("dimension",e.ndim)

[90 90 90 90 90 90 90 90 90 90]
dimension 1


In [ ]:
e=np.full((100),80)
print(e)
print("dimension",e.ndim)

[80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80
 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80
 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80
 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80
 80 80 80 80]
dimension 1


#create a 2D array

In [ ]:
e=np.full((10,10),80)
print(e)
print("dimension",e.ndim)

[[80 80 80 80 80 80 80 80 80 80]
 [80 80 80 80 80 80 80 80 80 80]
 [80 80 80 80 80 80 80 80 80 80]
 [80 80 80 80 80 80 80 80 80 80]
 [80 80 80 80 80 80 80 80 80 80]
 [80 80 80 80 80 80 80 80 80 80]
 [80 80 80 80 80 80 80 80 80 80]
 [80 80 80 80 80 80 80 80 80 80]
 [80 80 80 80 80 80 80 80 80 80]
 [80 80 80 80 80 80 80 80 80 80]]
dimension 2


In [ ]:
e=np.full((1,20),80)
print(e)
print("dimension",e.ndim)

[[80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80]]
dimension 2


#create a 2*2 identity matrix

In [ ]:
f=np.eye(4)
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#3*3

In [ ]:
f=np.eye(9)
print(f)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


#4*4


In [ ]:
f=np.eye(16)
print(f)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


#5*5

In [ ]:
f=np.eye(25)
print(f)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.

#2*3

In [18]:
f=np.eye(6)
print(f)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


#2*4

In [19]:
f=np.eye(8)
print(f)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


#2*5

In [20]:
f=np.eye(10)
print(f)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


#3*2

In [22]:
f=np.eye(6)
print(f)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


#3*4

In [23]:
f=np.eye(12)
print(f)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


# create an array with random values

In [ ]:
np.random.random((4,1,5))

array([[[0.6613656 , 0.30770666, 0.41176962, 0.73930246, 0.94247475]],

       [[0.26568634, 0.84994107, 0.76885465, 0.71421849, 0.1571088 ]],

       [[0.58020642, 0.93511221, 0.35601959, 0.57828098, 0.57711707]],

       [[0.95411542, 0.53619122, 0.39559743, 0.19932051, 0.49642382]]])

In [ ]:
import numpy as np

In [ ]:
np.random.randint(1,40)

17

In [ ]:
np.random.randint(1,500)


361

#To find shape of an array

In [ ]:
arr=np.array([[4,4,4,4,4,4,4],[5,5,5,5,5,5,5],[8,8,8,8,8,8,8]])
print(arr.shape)

(3, 7)


#To find no of elements in array

In [ ]:
arr=np.array([[4,4,4,4,4,4,4],[5,5,5,5,5,5,5],[8,8,8,8,8,8,8]])
print(arr.size)

21


#To find length of array

In [ ]:
arr=np.array([[4,4,4,4,4,4,4],[5,5,5,5,5,5,5],[8,8,8,8,8,8,8]])
print(len(arr))

3


In [34]:
arr=np.array([[4,4],[5,5],[8,8]])
print(len(arr))
arr=np.array([[[60,50,80],[20,60,30],[40,67,34]]])
print(len(arr))

3
1
